language: rust

rust:
  - 1.26.0
  - stable
  - beta

cache:
  cargo: true

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - cargo test